### ISSUE TITLE
Unable to run diagnostics with v2.4.152

### ISSUE THREAD

**Issue by clopmz** [coolacid/docker-misp#156]
Hi all,

After updating my docker images to release v2.4.152, I can not run diagnostics options. The following errors appears:

2022-01-11 08:24:09 Error: [Exception] DateTime::__construct() [<a href='http://php.net/datetime.construct'>datetime.construct</a>]: Failed to parse time string (1639018277) at position 7 (2): Unexpected character
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/SecurityAudit.php(470): DateTime->__construct('1639018277')
#1 /var/www/MISP/app/Lib/Tools/SecurityAudit.php(387): SecurityAudit->getKernelBuild()
#2 /var/www/MISP/app/Lib/Tools/SecurityAudit.php(272): SecurityAudit->system(Array)
#3 /var/www/MISP/app/Controller/ServersController.php(1187): SecurityAudit->run(Object(Server))
#4 [internal function]: ServersController->serverSettings('diagnostics')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2022-01-11 08:24:16 Error: [Exception] DateTime::__construct() [<a href='http://php.net/datetime.construct'>datetime.construct</a>]: Failed to parse time string (1639018277) at position 7 (2): Unexpected character
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/SecurityAudit.php(470): DateTime->__construct('1639018277')
#1 /var/www/MISP/app/Lib/Tools/SecurityAudit.php(387): SecurityAudit->getKernelBuild()
#2 /var/www/MISP/app/Lib/Tools/SecurityAudit.php(272): SecurityAudit->system(Array)
#3 /var/www/MISP/app/Controller/ServersController.php(1187): SecurityAudit->run(Object(Server))
#4 [internal function]: ServersController->serverSettings('diagnostics')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2022-01-11 08:26:01 Error: [Exception] DateTime::__construct() [<a href='http://php.net/datetime.construct'>datetime.construct</a>]: Failed to parse time string (1639018277) at position 7 (2): Unexpected character
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/SecurityAudit.php(470): DateTime->__construct('1639018277')
#1 /var/www/MISP/app/Lib/Tools/SecurityAudit.php(387): SecurityAudit->getKernelBuild()
#2 /var/www/MISP/app/Lib/Tools/SecurityAudit.php(272): SecurityAudit->system(Array)
#3 /var/www/MISP/app/Controller/ServersController.php(1187): SecurityAudit->run(Object(Server))
#4 [internal function]: ServersController->serverSettings('diagnostics')
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#8 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}

Regards.

**Comment by ph3nce** [comment]
This is mentioned in https://github.com/MISP/MISP/issues/8078 and https://github.com/MISP/MISP/issues/8057
Seems to be fixed in this commit https://github.com/MISP/MISP/commit/40f83a0329e5dde04f45ec8f00c281fd1b2c9c6c
I manually made this change to `SecurityAudit.php` in my docker-misp container and the Diagnostics page works now.

**Comment by coolacid** [comment]
Closing as upstream bug.
