### ISSUE TITLE
fetch_feed failed

### ISSUE THREAD

**Issue by henrythanhtran** [coolacid/docker-misp#166]
Attempting to fetch feed Fata for CIRCL OSINT Feed and fails. Any ideas?
![Screen Shot 2022-03-28 at 4 00 06 PM](https://user-images.githubusercontent.com/91563994/160477538-b738a23c-4493-4b03-be02-20d956aaa197.png)

**Comment by coolacid** [comment]
What does the error log say?

**Comment by henrythanhtran** [comment]
```
stream_socket_client(): unable to connect to ssl://www.circl.lu:443 (Unknown error)
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/HttpSocketExtended.php(147): CakeSocket->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(400): HttpSocketExtended->connect()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write()
#3 /var/www/MISP/app/Lib/Tools/HttpSocketExtended.php(186): HttpSocket->request()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(464): HttpSocketExtended->request()
#5 /var/www/MISP/app/Model/Feed.php(1997): HttpSocket->get()
#6 /var/www/MISP/app/Model/Feed.php(1958): Feed->getFollowRedirect()
#7 /var/www/MISP/app/Model/Feed.php(262): Feed->feedGetUriRemote()
#8 /var/www/MISP/app/Model/Feed.php(166): Feed->getRemoteManifest()
#9 /var/www/MISP/app/Model/Feed.php(1096): Feed->getNewEventUuids()
#10 /var/www/MISP/app/Console/Command/ServerShell.php(249): Feed->downloadFromFeedInitiator()
#11 /var/www/MISP/app/Console/Command/AppShell.php(43): ServerShell->fetchFeed()
#12 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#13 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#14 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#15 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#16 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#17 {main}
2022-03-28 19:59:42 Error: Could not get new event uuids for feed 2.
[Exception] Fetching the 'https://www.botvrij.eu/data/feed-osint/manifest.json' failed with exception: stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
stream_socket_client(): Failed to enable crypto
stream_socket_client(): unable to connect to ssl://www.botvrij.eu:443 (Unknown error)
Stack Trace:
#0 /var/www/MISP/app/Model/Feed.php(262): Feed->feedGetUriRemote()
#1 /var/www/MISP/app/Model/Feed.php(166): Feed->getRemoteManifest()
#2 /var/www/MISP/app/Model/Feed.php(1096): Feed->getNewEventUuids()
#3 /var/www/MISP/app/Console/Command/ServerShell.php(249): Feed->downloadFromFeedInitiator()
#4 /var/www/MISP/app/Console/Command/AppShell.php(43): ServerShell->fetchFeed()
#5 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#6 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#7 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#8 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#10 {main}[SocketException] stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
stream_socket_client(): Failed to enable crypto
stream_socket_client(): unable to connect to ssl://www.botvrij.eu:443 (Unknown error)
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/HttpSocketExtended.php(147): CakeSocket->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(400): HttpSocketExtended->connect()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write()
#3 /var/www/MISP/app/Lib/Tools/HttpSocketExtended.php(186): HttpSocket->request()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(464): HttpSocketExtended->request()
#5 /var/www/MISP/app/Model/Feed.php(1997): HttpSocket->get()
#6 /var/www/MISP/app/Model/Feed.php(1958): Feed->getFollowRedirect()
#7 /var/www/MISP/app/Model/Feed.php(262): Feed->feedGetUriRemote()
#8 /var/www/MISP/app/Model/Feed.php(166): Feed->getRemoteManifest()
#9 /var/www/MISP/app/Model/Feed.php(1096): Feed->getNewEventUuids()
#10 /var/www/MISP/app/Console/Command/ServerShell.php(249): Feed->downloadFromFeedInitiator()
#11 /var/www/MISP/app/Console/Command/AppShell.php(43): ServerShell->fetchFeed()
#12 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#13 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#14 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform()
#15 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work()
#16 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker()
#17 {main}
```

**Comment by coolacid** [comment]
It's unable to verify the certificates. Did you change something? Do you have a inline proxy?

**Comment by henrythanhtran** [comment]
All I did was change the config.php file baseurl to my local IP rather than localhost. 
I am using an inline proxy. Does that mess up certificate verification?

**Comment by coolacid** [comment]
Yes. Inline proxies would change the SSL cert used to secure the connection.

**Comment by henrythanhtran** [comment]
How would I remedy this situation if I want to continue to use the inline proxy?
Also thank you for the fast responses! You're awesome.

**Comment by coolacid** [comment]
That's unsupported here. 

But you could modify the docker image to include what ever CA cert you're using to sign SSL via your proxy into the approved CA list. 

Alternatively, you'd need to ask MISP team if there is a way to disable SSL checking.

**Comment by henrythanhtran** [comment]
I've added cert.pem, key.pem, and ca.pem to /etc/ssl/certs/ and appended the CA cert to the end of the /etc/ssl/certs/ca-certificates.crt within the docker image, are there any changes/additions that I need to make for this to work?

**Comment by coolacid** [comment]
Sorry for the delay. Unfortunately, changing the certs is out side of the scope of the project. My recommendation might be to use this image as a base image for your own image, and add the certs per debian's documentation.
