### ISSUE TITLE
v2.4.170a requires Clean model cache after deployment

### ISSUE THREAD

**Issue by Applenice** [coolacid/docker-misp#219]
After the deployment of v2.4.170a, we need to clean the model cache, here are the steps to reproduce and the corresponding solution.

**Reproduction steps:**
1. load image
```
REPOSITORY             TAG                 IMAGE ID       CREATED       SIZE
coolacid/misp-docker   core-v2.4.170a      129e26e848cf   9 days ago    1.65GB
coolacid/misp-docker   modules-v2.4.170a   726d3b8c7ae2   9 days ago    811MB
namshi/smtp            latest              56bd3496dfd8   2 years ago   209MB
mysql                  8.0.19              0c27e8e5fcfa   3 years ago   546MB
redis                  5.0.6               de25a81a5a0b   3 years ago   98.2MB
```
2. git clone repo and cd repo, modify docker-compose.yml image tag: 
`core-latest` to `core-v2.4.170a`
`modules-latest` to `modules-v2.4.170a`

3. docker-compose up -d
4. login
5. The following scenarios can be triggered `An Internal Error Has Occurred.`
- click `Administration` -> `Workflows` or  `Over-Correlating values`
- click `Sync Actions` -> `Cerebrates` or `List Taxii Servers`
- Enable feeds and Fetch all Events

In `/var/www/MISP/app/tmp/logs/error.log`  can see similar `Error: [MissingControllerException]` error message, eg:
```
              Error: [MissingTableException] Table workflows for model Workflow was not found in datasource default.
Exception Attributes: array (
  'table' => 'workflows',
  'class' => 'Workflow',
  'ds' => 'default',
)
Request URL: /workflows/triggers
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): Model->getDataSource()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#3 /var/www/MISP/app/Model/Workflow.php(1173): Model->find()
#4 /var/www/MISP/app/Model/Workflow.php(345): Workflow->fetchWorkflows()
#5 /var/www/MISP/app/Controller/WorkflowsController.php(188): Workflow->attachWorkflowToTriggers()
#6 [internal function]: WorkflowsController->triggers()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#10 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#11 {main}
```

**Solutions:**
Click `Administration` -> `Server Settings & Maintenanc` -> `diagnostics` -> `clean cache`, it will be back to normal.

Hope it will be useful to you and others, Thank you for the docker image.😀

**Comment by Nicolas-Pellletier** [comment]
Thanks for sharing ❤️
