### ISSUE TITLE
MISP database issue after fresh install

### ISSUE THREAD

**Issue by gaglimax** [coolacid/docker-misp#63]
Hi, 

I just tried to install MISP with the compose file. Everything seems good but the diagnostic tools shows database issue :
![image](https://user-images.githubusercontent.com/32092271/91981657-74f6e100-ed29-11ea-8030-755a7f1908fb.png)

If I run the SQL query adviced for the first line, it doesn't solve the warning :
```
mysql> ALTER TABLE `admin_settings` MODIFY COLUMN `id` int(11) NOT NULL auto_increment;
Query OK, 0 rows affected, 1 warning (0.02 sec)
Records: 0  Duplicates: 0  Warnings: 1

mysql> show warnings;
+---------+------+------------------------------------------------------------------------------+
| Level   | Code | Message                                                                      |
+---------+------+------------------------------------------------------------------------------+
| Warning | 1681 | Integer display width is deprecated and will be removed in a future release. |
+---------+------+------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

Also, when I tried to import a STIX 1.1.1 format file using the import module, I ran to an Internal Server Error. Here is the logs file :
```
2020-09-02 12:20:35 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'misp.GalaxyCluster.value' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Request URL: /events/upload_stix
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `GalaxyC...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `GalaxyC...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `GalaxyC...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(GalaxyCluster), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Model/Event.php(5803): Model->find('all', Array)
#7 /var/www/MISP/app/Model/Event.php(5747): Event->__getTagNamesFromSynonyms('/var/www/MISP/a...')
#8 /var/www/MISP/app/Controller/EventsController.php(2159): Event->upload_stix(Array, '/var/www/MISP/a...', 'nhCxVUbNg8PO', 'STIX 1.1', 'exportIOC (1).x...', '0')
#9 [internal function]: EventsController->upload_stix()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
```

After googling some stuff, I tried so run this query :
`SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`

Then, the Internal Server Error doesn't occur again but I have this error message :
`Could not import STIX document: Issues while loading the stix file. Please check whether the dependencies for STIX are met via the diagnostic tool.`

In the diagnostic tool, everything is fine.

Thanks for any help,

**Comment by gaglimax** [comment]
Just forget the STIX issue, it was because the file was in the wrong format.

**Comment by coolacid** [comment]
Are you using the mysql instance in the docker-compose, or an external mysql instance?

**Comment by gaglimax** [comment]
The one in the compose file.

**Comment by coolacid** [comment]
So, this is specifically a "bug" in MISP directly, not the docker container - But some background:
- Most importantly, this does not affect MISP in anyway. The INT(x) is a display item only, which MISP doesn't make use of.
- This is a difference in how MySQL will use the INT(x) and as you noted depreciated. 

An issue should be opened in the MISP project noting that it's a depreciated option. I can do that on your behalf if you'd like.

**Comment by gaglimax** [comment]
Ok thanks. Yes you can open an issue on my behalf in the MISP project.
