### ISSUE TITLE
REST API -> Error: An Internal Error Has Occurred.

### ISSUE THREAD

**Issue by ITSEC-DACHSER** [coolacid/docker-misp#68]
We have problems with the REST API. It throws an error with every request.
Here is a screenshot:
![misp-error](https://user-images.githubusercontent.com/50357205/96724618-51a6f480-13b0-11eb-9172-838250cc2729.PNG)

Here is the error log:
```
2020/10/21 12:47:57 [error] 231#231: *286 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught InternalErrorException: Internal Server Error in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php:261

Stack trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(256, '[CakeException]...', '/var/www/MISP/a...', 138)
#1 [internal function]: ErrorHandler::handleError(256, '[CakeException]...', '/var/www/MISP/a...', 138, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(138): trigger_error('[CakeException]...', 256)
#3 [internal function]: ErrorHandler::handleException(Object(SocketException))

}
thrown in /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php on line 261" while reading response header from upstream, client: 10.36.63.185, server: , request: "POST /servers/rest HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "docker01.subdomain.domain.tld"
```
We still have a dedicated server for MISP, there the API call works without problems.
We are thankful for every tip.

**Comment by coolacid** [comment]
What were you doing at the time? What API call were you doing? This appears to be the WebUI, not a Rest Call.

**Comment by ITSEC-DACHSER** [comment]
Thanks for your quick response.

Here is a screenshot about a simple api call that should work. If i click on "Run query" i get the error in the post above.
The same query runs fine on our dedicated productive server.
![docker-api](https://user-images.githubusercontent.com/50357205/96830393-ad6a8f80-143b-11eb-8c73-c464172cae9c.PNG)
No worry about the Token. It´s just a dev machine that we destroy again.

**//EDIT**
We were able to query the API with the pyMISP library successfully on both Server (docker & productive). 
So it looks like - it´s "only" a WebUI error !?
