### ISSUE TITLE
500 error listing attributes and tags

### ISSUE THREAD

**Issue by pemontto** [coolacid/docker-misp#79]
With the basic setup after fetching some feeds it's not possible to list tags or attributes. Looks like it's related to MISP/MISP#1894.

Error messages from `/var/www/MISP/app/tmp/logs/error.log`:
```shell
2020-12-30 10:26:51 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'misp.Sighting.date_sighting' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Request URL: /attributes/index
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `Sightin...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `Sightin...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `Sightin...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(Sighting), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Model/Sighting.php(331): Model->find('all', Array)
#7 /var/www/MISP/app/Model/Sighting.php(277): Sighting->fetchGroupedSightings(Array, Array)
#8 /var/www/MISP/app/Controller/AttributesController.php(1700): Sighting->attributesStatistics(Array, Array)
#9 /var/www/MISP/app/Controller/AttributesController.php(97): AttributesController->__searchUI(Array)
#10 [internal function]: AttributesController->index()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(AttributesController), Array)
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AttributesController), Object(CakeRequest))
#14 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
2020-12-30 10:27:03 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'misp.Sighting.date_sighting' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Request URL: /tags/index
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `EventTa...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `EventTa...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `EventTa...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(Sighting), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('all', Array)
#6 /var/www/MISP/app/Model/Sighting.php(367): Model->find('all', Array)
#7 /var/www/MISP/app/Model/Sighting.php(230): Sighting->fetchGroupedSightingsForTags(Array, Array, 'event')
#8 /var/www/MISP/app/Controller/TagsController.php(112): Sighting->tagsSparkline(Array, Array, '0')
#9 [internal function]: TagsController->index()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(TagsController), Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(TagsController), Object(CakeRequest))
#13 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
```
The only way I can get this resolved is by disabling the default `ONLY_FULL_GROUP_BY` setting in MySQL.

The temporary workaround until those queries are fixed in MISP is:
```sql
SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
```

**Comment by coolacid** [comment]
Thanks, yeah, looking at the MISP tagged issue it does appear to be upstream - of course, it's exaggerated here because of the docker-compose using a much newer MySQL version. I really shouldn't roll back to an earlier version since that would break people.

**Comment by coolacid** [comment]
@pemontto I checked with the MISP team via GITTER and they would like you to test with the latest version. If it's still a problem, as of 2.4.137, please let me know here, and in their ticket.

**Comment by Ari-R** [comment]
Hi, I think I am having this issue. When I try to "import from" ,select a file like stix 2,0 etc when uploading it gives says "An internal error has occurred..". Checking the error log it gives,

2021-11-08 05:14:27 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is no
t in GROUP BY clause and contains nonaggregated column 'misp.GalaxyCluster.value' which is not functionally dependent on columns in
GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

I have been trying to use: 
SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
 but its giving me a synatx error.

**Comment by coolacid** [comment]
@Ari-R This image doesn't change anything from upstream, if there is a MySQL error, it's an upstream issue.
